CREATE TABLE CLIENTES (
	CPF VARCHAR(11) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    FONE VARCHAR(15) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    PRIMARY KEY (CPF)
);